import type {
  CommunityEventApiItem,
  CommunityEventCategory,
} from "@/features/community/types/community-event";
import { fallbackEventCategories } from "@/features/community/constants/event-categories";

const culturalEventsCategory =
  fallbackEventCategories[0] as CommunityEventCategory;
const workshopsCategory = fallbackEventCategories[1] as CommunityEventCategory;
const ceremoniesCategory = fallbackEventCategories[2] as CommunityEventCategory;
const socialEventsCategory =
  fallbackEventCategories[3] as CommunityEventCategory;

function createFallbackEvent(
  event: Omit<CommunityEventApiItem, "category" | "_count"> & {
    registrations: number;
    category: CommunityEventCategory;
  },
): CommunityEventApiItem {
  return {
    id: event.id,
    title: event.title,
    description: event.description,
    categoryId: event.categoryId,
    startDateTime: event.startDateTime,
    endDateTime: event.endDateTime,
    locationType: event.locationType,
    location: event.location,
    meetingUrl: event.meetingUrl,
    maxCapacity: event.maxCapacity,
    isFeatured: event.isFeatured,
    externalUrl: event.externalUrl,
    createdAt: event.createdAt,
    updatedAt: event.updatedAt,
    category: event.category,
    _count: {
      registrations: event.registrations,
    },
    registrationCount: event.registrations,
  };
}

export const fallbackUpcomingEvents: CommunityEventApiItem[] = [
  createFallbackEvent({
    id: "fallback-winter-solstice-ceremony",
    title: "Winter Solstice Ceremony",
    description:
      "Join us for our annual Winter Solstice ceremony honoring our ancestors and celebrating the return of longer days. The ceremony includes traditional songs, prayers, and a community feast for all families.",
    categoryId: culturalEventsCategory.id,
    startDateTime: "2026-12-21T17:00:00.000Z",
    endDateTime: "2026-12-21T21:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Cayinabon Ceremonial Grounds",
    meetingUrl: null,
    maxCapacity: 300,
    isFeatured: true,
    externalUrl: null,
    createdAt: "2026-04-30T12:00:00.000Z",
    updatedAt: "2026-04-30T12:00:00.000Z",
    category: culturalEventsCategory,
    registrations: 247,
  }),
  createFallbackEvent({
    id: "fallback-ancestral-drum-circle",
    title: "Ancestral Drum Circle",
    description:
      "An evening of rhythm, oral history, and intergenerational connection centered around traditional Taíno drumming and shared remembrance.",
    categoryId: culturalEventsCategory.id,
    startDateTime: "2026-09-18T18:00:00.000Z",
    endDateTime: "2026-09-18T20:30:00.000Z",
    locationType: "PHYSICAL",
    location: "Yucayeke Pavilion",
    meetingUrl: null,
    maxCapacity: 180,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-02T10:00:00.000Z",
    updatedAt: "2026-05-02T10:00:00.000Z",
    category: culturalEventsCategory,
    registrations: 164,
  }),
  createFallbackEvent({
    id: "fallback-boriken-heritage-festival",
    title: "Boriken Heritage Festival",
    description:
      "A day-long celebration featuring food, music, dance, and cultural education that highlights living Taíno traditions across the community.",
    categoryId: culturalEventsCategory.id,
    startDateTime: "2026-08-08T14:00:00.000Z",
    endDateTime: "2026-08-08T19:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Island Heritage Park",
    meetingUrl: null,
    maxCapacity: 500,
    isFeatured: true,
    externalUrl: null,
    createdAt: "2026-05-03T09:30:00.000Z",
    updatedAt: "2026-05-03T09:30:00.000Z",
    category: culturalEventsCategory,
    registrations: 21,
  }),
  createFallbackEvent({
    id: "fallback-sacred-foodways-gathering",
    title: "Sacred Foodways Gathering",
    description:
      "Members come together to prepare traditional dishes, share agricultural knowledge, and preserve ancestral food practices.",
    categoryId: culturalEventsCategory.id,
    startDateTime: "2026-10-11T11:00:00.000Z",
    endDateTime: "2026-10-11T14:30:00.000Z",
    locationType: "PHYSICAL",
    location: "Community Teaching Kitchen",
    meetingUrl: null,
    maxCapacity: 120,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-04T11:00:00.000Z",
    updatedAt: "2026-05-04T11:00:00.000Z",
    category: culturalEventsCategory,
    registrations: 97,
  }),
  createFallbackEvent({
    id: "fallback-art-craft-workshop",
    title: "Art & Craft Workshop",
    description:
      "A hands-on session where members learn weaving, beadwork, and symbolic design patterns inspired by Taíno visual traditions.",
    categoryId: workshopsCategory.id,
    startDateTime: "2026-06-15T10:00:00.000Z",
    endDateTime: "2026-06-15T13:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Art Center",
    meetingUrl: null,
    maxCapacity: 20,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-01T10:00:00.000Z",
    updatedAt: "2026-05-01T10:00:00.000Z",
    category: workshopsCategory,
    registrations: 188,
  }),
  createFallbackEvent({
    id: "fallback-language-revival-lab",
    title: "Language Revival Lab",
    description:
      "Collaborative workshop focused on pronunciation, vocabulary recovery, and practical use of preserved Taíno language terms.",
    categoryId: workshopsCategory.id,
    startDateTime: "2026-07-09T18:00:00.000Z",
    endDateTime: "2026-07-09T20:00:00.000Z",
    locationType: "HYBRID",
    location: "Digital Learning Studio",
    meetingUrl: "https://example.com/language-revival-lab",
    maxCapacity: 80,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-02T13:00:00.000Z",
    updatedAt: "2026-05-02T13:00:00.000Z",
    category: workshopsCategory,
    registrations: 142,
  }),
  createFallbackEvent({
    id: "fallback-regalia-design-intensive",
    title: "Regalia Design Intensive",
    description:
      "A guided making session on ceremonial attire, symbolism, natural materials, and respectful contemporary adaptation.",
    categoryId: workshopsCategory.id,
    startDateTime: "2026-09-05T12:30:00.000Z",
    endDateTime: "2026-09-05T16:30:00.000Z",
    locationType: "PHYSICAL",
    location: "Makers Hall",
    meetingUrl: null,
    maxCapacity: 60,
    isFeatured: true,
    externalUrl: null,
    createdAt: "2026-05-04T08:00:00.000Z",
    updatedAt: "2026-05-04T08:00:00.000Z",
    category: workshopsCategory,
    registrations: 176,
  }),
  createFallbackEvent({
    id: "fallback-youth-storytelling-studio",
    title: "Youth Storytelling Studio",
    description:
      "An intergenerational workshop where youth members create visual and spoken stories rooted in family memory and Indigenous identity.",
    categoryId: workshopsCategory.id,
    startDateTime: "2026-10-19T16:00:00.000Z",
    endDateTime: "2026-10-19T18:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Learning Commons",
    meetingUrl: null,
    maxCapacity: 45,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-05T14:30:00.000Z",
    updatedAt: "2026-05-05T14:30:00.000Z",
    category: workshopsCategory,
    registrations: 64,
  }),
  createFallbackEvent({
    id: "fallback-spiritual-chanting-ceremony",
    title: "Spiritual Chanting Ceremony",
    description:
      "A dawn gathering devoted to collective chanting, stillness, and spiritual reflection led by community ceremonial keepers.",
    categoryId: ceremoniesCategory.id,
    startDateTime: "2026-07-10T05:00:00.000Z",
    endDateTime: "2026-07-10T07:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Temple Grounds",
    meetingUrl: null,
    maxCapacity: 70,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-01T10:05:00.000Z",
    updatedAt: "2026-05-01T10:05:00.000Z",
    category: ceremoniesCategory,
    registrations: 238,
  }),
  createFallbackEvent({
    id: "fallback-new-moon-water-blessing",
    title: "New Moon Water Blessing",
    description:
      "A guided blessing ceremony focused on purification, prayer, and offering as the community gathers beside sacred waters.",
    categoryId: ceremoniesCategory.id,
    startDateTime: "2026-06-29T19:30:00.000Z",
    endDateTime: "2026-06-29T21:00:00.000Z",
    locationType: "PHYSICAL",
    location: "River Ceremony Site",
    meetingUrl: null,
    maxCapacity: 90,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-02T09:45:00.000Z",
    updatedAt: "2026-05-02T09:45:00.000Z",
    category: ceremoniesCategory,
    registrations: 154,
  }),
  createFallbackEvent({
    id: "fallback-harvest-thanksgiving-rite",
    title: "Harvest Thanksgiving Rite",
    description:
      "A ceremonial gathering of gratitude honoring land, harvest, and ancestors through prayer, music, and offerings.",
    categoryId: ceremoniesCategory.id,
    startDateTime: "2026-11-14T16:00:00.000Z",
    endDateTime: "2026-11-14T18:30:00.000Z",
    locationType: "PHYSICAL",
    location: "Harvest Circle",
    meetingUrl: null,
    maxCapacity: 160,
    isFeatured: true,
    externalUrl: null,
    createdAt: "2026-05-03T16:00:00.000Z",
    updatedAt: "2026-05-03T16:00:00.000Z",
    category: ceremoniesCategory,
    registrations: 205,
  }),
  createFallbackEvent({
    id: "fallback-sunrise-prayer-observance",
    title: "Sunrise Prayer Observance",
    description:
      "A quiet early-morning ceremony for communal prayer, grounding, and seasonal intention-setting as the sun rises.",
    categoryId: ceremoniesCategory.id,
    startDateTime: "2026-08-22T05:30:00.000Z",
    endDateTime: "2026-08-22T06:45:00.000Z",
    locationType: "PHYSICAL",
    location: "Eastern Lookout",
    meetingUrl: null,
    maxCapacity: 85,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-05T07:15:00.000Z",
    updatedAt: "2026-05-05T07:15:00.000Z",
    category: ceremoniesCategory,
    registrations: 73,
  }),
  createFallbackEvent({
    id: "fallback-startup-networking-night",
    title: "Startup Networking Night",
    description:
      "An evening for entrepreneurs, creatives, and organizers to exchange ideas, meet collaborators, and strengthen economic ties.",
    categoryId: socialEventsCategory.id,
    startDateTime: "2026-08-01T17:00:00.000Z",
    endDateTime: "2026-08-01T20:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Business Hub",
    meetingUrl: null,
    maxCapacity: 100,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-01T10:20:00.000Z",
    updatedAt: "2026-05-01T10:20:00.000Z",
    category: socialEventsCategory,
    registrations: 129,
  }),
  createFallbackEvent({
    id: "fallback-community-healing-gathering",
    title: "Community Healing Gathering",
    description:
      "Gather with community members for an evening of reflection, drumming, storytelling, and shared prayer. This circle is open to all families seeking connection and support.",
    categoryId: socialEventsCategory.id,
    startDateTime: "2026-12-28T18:30:00.000Z",
    endDateTime: "2026-12-28T20:30:00.000Z",
    locationType: "PHYSICAL",
    location: "Boricua Heritage Community Hall",
    meetingUrl: null,
    maxCapacity: 220,
    isFeatured: true,
    externalUrl: null,
    createdAt: "2026-05-01T15:00:00.000Z",
    updatedAt: "2026-05-01T15:00:00.000Z",
    category: socialEventsCategory,
    registrations: 183,
  }),
  createFallbackEvent({
    id: "fallback-family-reunion-picnic",
    title: "Family Reunion Picnic",
    description:
      "A relaxed social event with shared meals, games, and introductions for new and longtime members of the community.",
    categoryId: socialEventsCategory.id,
    startDateTime: "2026-07-26T13:00:00.000Z",
    endDateTime: "2026-07-26T17:00:00.000Z",
    locationType: "PHYSICAL",
    location: "Unity Meadow",
    meetingUrl: null,
    maxCapacity: 260,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-03T12:15:00.000Z",
    updatedAt: "2026-05-03T12:15:00.000Z",
    category: socialEventsCategory,
    registrations: 214,
  }),
  createFallbackEvent({
    id: "fallback-member-welcome-mixer",
    title: "Member Welcome Mixer",
    description:
      "A social welcome event for new members to meet leadership, ask questions, and build first connections inside the Taíno Nation network.",
    categoryId: socialEventsCategory.id,
    startDateTime: "2026-06-20T18:00:00.000Z",
    endDateTime: "2026-06-20T20:00:00.000Z",
    locationType: "HYBRID",
    location: "Community Commons",
    meetingUrl: "https://example.com/member-welcome-mixer",
    maxCapacity: 140,
    isFeatured: false,
    externalUrl: null,
    createdAt: "2026-05-04T18:00:00.000Z",
    updatedAt: "2026-05-04T18:00:00.000Z",
    category: socialEventsCategory,
    registrations: 121,
  }),
];

export function getFallbackUpcomingEventsByCategory(
  categoryKey?: string | null,
) {
  if (!categoryKey) {
    return fallbackUpcomingEvents;
  }

  return fallbackUpcomingEvents.filter(
    (event) => event.category?.key === categoryKey,
  );
}
